version: '3'

services:
  postgresql:
    container_name: database
    image: postgres:latest
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./src/db/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  imdb_scraping:
    container_name: scraping
    image: selenium/standalone-chrome:latest
    build:
      context: src/scraping    
    restart: always
    depends_on:
      - postgresql
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

  dashboard:
    container_name: dash-app
    build:
      context: src/app
    restart: always
    ports:
      - 5000:8050
    depends_on:
      - postgresql
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}



volumes:
  postgres-vol:
