version: '3'

services:
  postgresql:
    image: postgres:latest
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./src/db/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    networks:
      - network

  dashboard:
    build:
      context: src/app
    container_name: dash-app
    restart: always
    ports:
      - 5000:8050
    networks:
      - network
    depends_on:
      - postgresql
    links:
      - postgresql:postgresql

  # database-scripts:
  #   image: scraping-infer-image
  #   build:
  #     context: ./database_scripts
  #   depends_on:
  #     - postgresql
  #   environment:
  #     POSTGRES_NAME: ${POSTGRES_NAME}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #     POSTGRES_PORT: ${POSTGRES_PORT}

volumes:
  postgres-vol:

networks:
  network:
    driver: bridge
